Repository RRK1000/OSMDashboard-Winter-2024-SOEN-6431, pull requests merged in 2024-02, with the labels that each got.

#2 Issue for Case Study #1 Deliverable Solved
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
Labels: Group 16

#4 refactor: merge if statement + use isEmpty()
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
Labels: Technical Debt, Group 16

#6 Rename Description on Track.java
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/Track.java
Labels: Technical Debt, Group 16

#10 Remove unnecessary comment
  src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
Labels: Technical Debt, Group 16

#15 remove unnecessary parenthesis around a parameter
  src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
Labels: Technical Debt, Group 16, code-quality

#16 changed some access point
  src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/TrackPoint.java
Labels: Technical Debt, Group 16
